ip_forward: true
permissions:
  default: null
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
servers:
  main-server:
    motd: '&1Just another BungeeCord - Forced Host'
    address: server:25565
    restricted: false
listeners:
- query_port: 25577
  priorities:
  - main-server
  force_default_server: true
  ping_passthrough: true